branch-defaults:
  default:
    environment: django-app-env
    group_suffix: null
  main:
    environment: polls-app
global:
  application_name: polls-app
  branch: null
  default_ec2_keyname: polls-app
  default_platform: Python 3.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
